server:
  port: 6754
aws:
  s3:
    bucketName: "sigmawholeimages"
    productImagesPath: "productimages"
    accessKeyId: "AKIAYM7POCIYE6VYIF2X"
    secretKey: "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"
spring:
  mail:
    host: smtp.gmail.com
    username: fuzen.ltd@gmail.com
    password: glzc dzwi kady fwqe
    display-name: Sigma Wholesale
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: fuzen.ltd@gmail.com
#    password: Test@123
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

  servlet:
    multipart:
      enabled: true
      max-request-size: 4GB
      max-file-size: 4GB
  jackson:
    serialization:
      fail_on_empty_beans: false
  datasource:
    username: admin
    password: rjpdeveloperteam
#    username: root
#    password: password
#    url: jdbc:mysql://localhost:3306/sigmawholesale
#    url: jdbc:mysql://localhost:3306/sigmawholesale
    url: jdbc:mysql://database-1.czqkiu2iqgip.us-east-2.rds.amazonaws.com:3306/sigmawholesale

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-circular-references: true

  application:
    name: sigma
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days


#    username: klikktec_user
#    password: Test123@123
#    url: jdbc:mysql://ncr1.int3rnet.net:3306/klikktec_sigmawholesale?useSSL=false&serverTimezone=UTC