server:
  port: 6755
aws:
  s3:
    bucketName: "sigmawholeimages"
    productImagesPath: "productimages"
    accessKeyId: "AKIAYM7POCIYE6VYIF2X"
    secretKey: "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"

spring:
  servlet:
    multipart:
      max-request-size: 4GB
      max-file-size: 4GB
  jackson:
    serialization:
      fail_on_empty_beans: false
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/sigmawholesale
#    url: jdbc:mysql://localhost:3306/sigmawholesalebackup
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: sigma
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days


#    username: klikktec_user
#    password: Test123@123
#    url: jdbc:mysql://ncr1.int3rnet.net:3306/klikktec_sigmawholesale?useSSL=false&serverTimezone=UTC